version: "3.4"

services:
  proxy:
    build: ./docker/nginx
    container_name: laravel-training-proxy
    volumes:
      - ./source:/usr/share/nginx/html
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    build: ./docker/mysql
    container_name: laravel-training-db
    environment:
      MYSQL_DATABASE: prototype
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    expose:
      - "3306"
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/data:/var/lib/mysql
  php:
    build: ./docker/php
    container_name: training-php-fpm
    volumes:
      - ./training-php:/var/www/html
    expose: 
      - "9000"